Update Chapter 02.1 missing daemon first run
I noticed following the guide everything was working perfectly, but running `bitcoin-cli getblockcount` showed this:
````
error: Could not connect to the server 127.0.0.1:8332

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
````
I just noticed the daemon was not started